### ISSUE TITLE
Won't load any WADs with spaces in paths

### ISSUE THREAD

**Issue by Xylemon** [qbasicer/qzdl#35]
On Slackware 14.1 using qZDL 3.2.2.3

**Comment by Xylemon** [comment]
Any update on this?

**Comment by qbasicer** [comment]
I don't recall receiving any logs or config file, did you send them?

**Comment by Xylemon** [comment]
Yes, look for, "Won't load any WADs with spaces in paths" from "xylem2020@gmail.com". If you need me to re-send the email I can.

**Comment by qbasicer** [comment]
It seems to have gone missing, please re-send and cc "qbasicer@gmail.com".
Thanks

On Thu, Mar 5, 2015 at 8:38 PM, Gethyn ThomasQuail <notifications@github.com

**Comment by maxlefou** [comment]
Why is this closed? The problem isn't fixed, i'm facing it right now...
I just made a test, using a wad into a path with no spaces, and the same one with a path with spaces. The one without spaces works just right while the other one is purely ignored by qzdl (but working perfectly when launching it in command line without qzdl)

[Here's the logs i got](https://pastebin.com/FLUwCcsH)
I noticed something strange though. The logs says `adding "/home/user/doom wads/AAK_WAQ.WAD"` and `couldn't open "/home/user/doom wads/AAK_WAQ.WAD"` so, it sounds the spaces are recognized since it doesn't says something like `couldn't open "/home/user/doom"` and `couldn't open "wads/AAK_WAQ.WAD"`

Anyway, it's a minor problem since you just need to put the wads in a spaceless path.
