### ISSUE TITLE
File paths (and presumably also file names) do not handle spaces or character encoding correctly

### ISSUE THREAD

**Issue by WildPenquin** [qbasicer/qzdl#62]
Hi,

I have brütal doom files in  a directory with exactly that: a ü as per somewhere I saw it written with umlauted u.

qzdm constructs a command line with "brÃÂ¼tal" in there instead of just "brütal".

Also, the frontend does not handle spaces in folder names correctly.

Easy fix: don't use any non (ASCII?) characters in your folder (or file) names, nor spaces.

However this is not 1996 anymore so I feel these should be handled correctly (at least the spaces).

This is on Linux, locale set as utf8 one  (fi_FI.UTF-8).

**Comment by duganchen** [comment]
I went out of my way to test with paths that have spaces, so can you please tell me a bit more about how paths with spaces aren't handled "correctly", and what breaks with paths that have spaces?

**Comment by duganchen** [comment]
Well, the "show command line" dialog box is working properly with "brütal doom". Does the issue with the command-line and the UTF-8 characters happen elsewhere?

![main](https://user-images.githubusercontent.com/447610/75630360-121c6580-5b9f-11ea-8f5c-e6cd003db2b0.png)
![commandline](https://user-images.githubusercontent.com/447610/75630362-16488300-5b9f-11ea-80a0-aa6f10846820.png)

**Comment by duganchen** [comment]
When I clicked Launch, YES it launched DOOM2 with Brutal DOOM.

The easiest explanation that comes to my mind is that you didn't test with the latest master. I assume that's not the case, so feel free to keep discussing this so that we can determine why you're getting the results you're getting.

If you're wondering why the screenshots have huge text, it's because I'm testing this on an HTPC.

**Comment by WildPenquin** [comment]
duganchen: Yes, you are right, the current master works perfectly. I was using an old version. 

Sorry about the noise!
