### ISSUE TITLE
Export to Batch file

### ISSUE THREAD

**Issue by DoomRater** [qbasicer/qzdl#64]
I think this is the only feature that Telefrag Mapspawn has over ZDL at the moment.  Maybe I should look into submitting a pull request...?  Everything necessary already seems to exist in code.

**Comment by duganchen** [comment]
I actually have full commit-and-push access to the main QZDL repository, so please enter the issue there. I'll see it. :)

There are two some caveats though:

* This is the first time I've heard of Telefrag mapspawn, and I can't even find it with a Google search
* I'm trying very hard to keep the current QZDL codebase free of anything that isn't cross-platform
* I'm not a Windows user; when I need to test stuff in Windows, I fire up a VM.

The long and short of it is that I'm not the person for this job. If you submit a pull request, I would let @qbasicer decide what to do with it, and not involve myself.

**Comment by duganchen** [comment]
Well, first, this is the main QZDL repository, so we wouldn't be entering pull request; we would be updating it directly. That said, if it were entirely up to me then the answer is no. I'm personally trying very, very hard to keep the current codebase free of any code that isn't cross-platform.

Also, QZDL already covers most cases where I could imagine "Export to batch file" (or something similar, like "Add to Steam") would be useful:

First, "Show Command Line", in the "ZDL" menu, gives you a command-line that you can copy-and-paste into a batch file, should you want one. It's not currently the same command that QZDL uses internally, but it's untouched from when I started contributing, and I assume it works.

In that menu,  there is also "Save .zdl". That saves the list of PWADs into an ini file with the .zdl extension. The idea is that you associate .zdl files with QZDL, so that when you double-click on an .zdl file, it launches QZDL with the list of PWADs populated. If you check ""Launch *.ZDL files transparently", then double-clicking on an .zdl file with launch DOOM with those PWADs active.

**Comment by DoomRater** [comment]
I'm surprised the software is cross platform at all.  Guess that shows just how far out of the loop I've been with ZDoom and GZDoom lately.

I saw the "Show command line" which is a bit of extra manual work to copy and paste into a command line.  Also in Windows, you cannot highlight the text in the popup window, ergo no way to copy the command or arguments which are shown on individual lines.

It might be more appropriate for me to convert .zdl to a batch file instead, as long as the file structure stays consistent.  That way any work I do can stay separate from QZDL and not affect people's ability to compile it.

**Comment by duganchen** [comment]
The text in "Show command line" is selectable now.
