### ISSUE TITLE
I there a way to disable mods?

### ISSUE THREAD

**Issue by Toadfield** [qbasicer/qzdl#67]
Does this exist and I am just to dumb to find it,or does it not exist?
That would be easier to just disable them instead of remove them entirely.

**Comment by duganchen** [comment]
Nope.

I'd ask a bit more about your "workflow" (as we professionals say), but what I'm picturing is that you're setting up a list of PWADs, and you want to quickly experiment to see what it's like without one of the mods in the middle of the list (say, the visor mod). You feel that this would be more efficient  if, say, there was a checkbox next to the visor mod that you could just uncheck, instead of removing the mod and potentially having to re-add it and move it back into position. Am I correct?

**Comment by Toadfield** [comment]
yes,you are absolutely correct

**Comment by duganchen** [comment]
Implementing this doesn't look too complicated. There's just the caveat that persisting it across runs of the program would require adding that information to the .ini files. Which would break compatibility with earlier versions.

I assume that's okay with everyone?

**Comment by duganchen** [comment]
@qbasicer I'm thinking that we can add a "disabled" key to the zdl.save section, which would look like:

    [zdl.save]
    file0=/path/to/visor.pk3
    file1=/path/to/blood.pk3
    file2=/path/to/brutaldoom.pk3
    disabled=file0,file1

What do you think?

**Comment by qbasicer** [comment]
@duganchen - this seems like a decent approach, easier to implement/maintain than some other options

**Comment by Midnoclose** [comment]
This would be a great addition to the software.
